name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clean verify -U org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=D5M4573R_dvja_614deb9d-dc99-4ee5-bdae-e2311b21f457 \
          -Dsonar.projectName='dvja'
