name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      # Clear Maven cache
      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Cache SonarQube dependencies
      - name: Cache SonarQube dependencies
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarqube
          restore-keys: |
            ${{ runner.os }}-sonarqube

      # Build and analyze with SonarQube
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clean verify -U org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=D5M4573R_dvja_614deb9d-dc99-4ee5-bdae-e2311b21f457 \
          -Dsonar.projectName='dvja'
